name = "fps-aim-diary"
compatibility_date = "2024-06-27"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "fps-aim-diary-db"
database_id = "bd5e489e-0815-4b94-b683-9a167a2dc64e"

# Build command is set in Cloudflare Pages dashboard
# command = "npm run build"