name = "fps-aim-diary"
compatibility_date = "2024-06-27"
pages_build_output_dir = "out"

[env.production]
name = "fps-aim-diary"

[[env.production.d1_databases]]
binding = "DB"
database_name = "fps-aim-diary-db"
database_id = ""

[build]
command = "npm run build"